# =========================================================================
# DDSurfer_Pred.py — DDParcel 推理主入口
# =========================================================================
# 这是 DDParcel 的核心推理脚本。
# 输入：4 个归一化后的 DTI 标量图（FA/Trace/MinEig/MidEig）
# 输出：FreeSurfer 格式的脑区分割（.mgz）
#
# === 三视角 2.5D 推理策略 ===
# 传统 3D 网络显存需求太高，纯 2D 网络缺少上下文信息。
# DDParcel 用「2.5D 多视角融合」折中：
#
# 1. 在三个正交方向（轴向/冠状/矢状）上各运行一次 2D 网络
# 2. 每个视角的网络输出对同一体素的预测概率
# 3. 三视角概率按权重 0.4:0.4:0.2 加权融合
# 4. 融合后的概率图取 argmax 得到最终标签
#
# 为什么矢状面权重只有 0.2？
# - 矢状面网络的类别数更少（54 vs 82），分辨率较低
# - 在中间矢状面附近效果较好，越往两侧越差
# - 给予较低权重以平衡三视角的贡献
#
# === 数据流 ===
# 文件名收集（*-dti-*-NormMasked.nii.gz）
#      ↓
# load_and_conform_image（统一到 256³ 空间）
#      ↓
# 轴状面推理（权重 0.4）→ 概率写入 pred_prob[0]
# 冠状面推理（权重 0.4）→ 概率写入 pred_prob[1]
# 矢状面推理（权重 0.2）→ 概率写入 pred_prob[2]
#      ↓
# argmax → 标签映射（内部索引 → FreeSurfer 标签）
#      ↓
# 半球纠错（基于白质质心的高斯平滑约束）
#      ↓
# 可选清理 → 保存 .mgz
# =========================================================================
import argparse
import time
import sys
import glob
import logging
import os
import copy
import nibabel as nib
import numpy as np

import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.utils.data.dataloader import DataLoader
from torchvision import transforms

from scipy.ndimage.filters import median_filter, gaussian_filter
from skimage.measure import regionprops
from skimage.measure import label
from collections import OrderedDict

from data_loader.load_neuroimaging_data import OrigDataThickSlices_Fused_Input
from data_loader.load_neuroimaging_data import map_label2aparc_aseg
from data_loader.load_neuroimaging_data import map_prediction_sagittal2full
from data_loader.load_neuroimaging_data import get_largest_cc
from data_loader.load_neuroimaging_data import load_and_conform_image

from data_loader.augmentation import ToTensorTest
from models.networks import FastSurferCNN_Fuse_Unet_v3_extended

HELPTEXT = """
DDSurfer: deep learning anatomical brain parcellation from diffusion MRI. \n

Authors: \n
Fan Zhang \n
Kang Ik Kevin Cho \n
Johanna Seitz-Holland \n
Lipeng Ning \n
Jon Haitz Legarreta \n
Yogesh Rathi \n
Carl-Fredrik Westin \n
Lauren J. O'Donnell \n
Ofer Pasternak

Date: 2023-07

Acknowledgement: This code is build upon FasterSurfer (deep-mi.org/research/fastsurfer)
"""


# =========================================================================
# 命令行参数解析
# =========================================================================
def options_parse():
    """
    命令行参数解析。

    关键点（初学者版）：
    1) 会自动在 --in_dir 下查找 `*-dti-*-NormMasked.nii.gz` 作为输入；
    2) 会自动拼接三视角权重路径（axial/coronal/sagittal）；
    3) 推理时类别数、通道数、batch_size 会覆盖为与官方权重一致的固定值。
    """
    parser = argparse.ArgumentParser(description=HELPTEXT)

    # 1. Options for the MRI volumes (name of in and output, order of interpolation if not conformed)
    parser.add_argument('--in_dir', dest='iname', help='input directory, generated by preprocessing.py', default='./testdata/HCP-100337-b1000/')
    parser.add_argument('--out_dir', dest='oname', help='output directory', default='./testdata/HCP-100337-b1000/')
    parser.add_argument('--weights_dir', dest='weights', help="path to pre-trained weights", default='./weights/')

    # 2. Options for model parameters setup (only change if model training was changed)
    parser.add_argument('--num_filters', type=int, default=64, help='Filter dimensions for DenseNet (all layers same). Default=64')
    parser.add_argument('--num_classes_ax_cor', type=int, default=79, help='Number of classes to predict in axial and coronal net, including background. Default=79')
    parser.add_argument('--num_classes_sag', type=int, default=51, help='Number of classes to predict in sagittal net, including background. Default=51')
    parser.add_argument('--num_channels', type=int, default=7, help='Number of input channels. Default=7 (thick slices)')
    parser.add_argument('--kernel_height', type=int, default=5, help='Height of Kernel (Default 5)')
    parser.add_argument('--kernel_width', type=int, default=5, help='Width of Kernel (Default 5)')
    parser.add_argument('--stride', type=int, default=1, help="Stride during convolution (Default 1)")
    parser.add_argument('--stride_pool', type=int, default=2, help="Stride during pooling (Default 2)")
    parser.add_argument('--pool', type=int, default=2, help='Size of pooling filter (Default 2)')

    # 3. Clean up and GPU/CPU options (disable cuda, change batchsize)
    parser.add_argument('--clean', dest='cleanup', help="Flag to clean up segmentation", action='store_true')
    parser.add_argument('--batch_size', type=int, default=8, help="Batch size for inference. Default: 8")
    parser.add_argument('--simple_run', action='store_true', default=True, help='Simplified run: only analyse one given image specified by --in_name (output: --out_name). Need to specify absolute path to both --in_name and --out_name if this option is chosen.')
    parser.add_argument('--no_cuda', action='store_true', default=False, help='disables CUDA training')
    parser.add_argument('--device', default='auto', choices=['auto', 'cpu', 'cuda', 'mps'],
                        help='inference device: auto, cpu, cuda, or mps (Apple Metal)')
    parser.add_argument('--gpu', default='0', help='GPU ID number(s), comma-separated (default: 0)')

    sel_option = parser.parse_args()

    if sel_option.iname[-1] == '/':
        sel_option.iname = sel_option.iname[:-1]
    subjectID = os.path.basename(sel_option.iname)

    # 从输入目录收集预处理后的标量模态文件。
    # glob 模式 `*-dti-*-NormMasked.nii.gz` 匹配：
    # - FractionalAnisotropy-Reg-NormMasked.nii.gz
    # - Trace-Reg-NormMasked.nii.gz
    # - MinEigenvalue-Reg-NormMasked.nii.gz
    # - MidEigenvalue-Reg-NormMasked.nii.gz
    # 注意：glob 返回的文件顺序是按文件名排序的，
    # 所以所有模态的顺序是固定的（取决于文件名）。
    sel_option.iname = sorted(glob.glob(os.path.join(sel_option.iname, '*-dti-*-NormMasked.nii.gz')))
    os.makedirs(sel_option.oname, exist_ok=True)
    sel_option.oname = os.path.join(sel_option.oname, subjectID + '-DDSurfer-wmparc-Reg.mgz')

    # 三视角的主融合网络权重文件
    sel_option.network_sagittal_path = os.path.join(sel_option.weights, 'Fused-Unet-v3-noMax-sagittal.pkl')
    sel_option.network_coronal_path = os.path.join(sel_option.weights, 'Fused-Unet-v3-noMax-coronal.pkl')
    sel_option.network_axial_path = os.path.join(sel_option.weights, 'Fused-Unet-v3-noMax-axial.pkl')

    # 各模态各视角的 backbone 子网络权重。
    # 4 模态 × 3 视角 = 12 个文件。
    # 每个 backbone 是一个独立的 FastSurferCNN_return_all 网络，
    # 只处理一个模态在一个视角下的输入。
    sel_option.backbone_sagittal_path = sorted(glob.glob(os.path.join(sel_option.weights, 'backbones', '*sagittal.pkl')))
    sel_option.backbone_coronal_path = sorted(glob.glob(os.path.join(sel_option.weights, 'backbones', '*coronal.pkl')))
    sel_option.backbone_axial_path = sorted(glob.glob(os.path.join(sel_option.weights, 'backbones', '*axial.pkl')))

    # 推理时固定使用与公开权重一致的参数配置。
    sel_option.num_classes_ax_cor = 82        # 轴状/冠状网络：82 个类别（含背景）
    sel_option.num_classes_sag = 54            # 矢状网络：54 个类别（更少的类别）
    sel_option.num_channels = 7                # 厚切片通道数
    sel_option.num_modality = len(sel_option.iname)  # 输入模态数（通常是 4）
    sel_option.batch_size = 4                  # 推理批次大小

    return sel_option


# =========================================================================
# run_network — 运行单个视角的推理
# =========================================================================
def run_network(img_filename, orig_data, prediction_probability, plane, ckpts, params_model, model, logger):
    """
    运行单个视角（Axial/Coronal/Sagittal）的推理并将结果写入全局概率张量。

    参数里最重要的是：
    - prediction_probability: 累加容器，形状约为 [分支数, 256,256,256, 类别数]
    - plane: 当前视角
    - ckpts: 当前视角的主权重文件

    处理流程：
    1. 创建对应视角的 DataLoader
    2. 加载预训练主网络权重（保持 backbone 不变）
    3. 逐 batch 推理
    4. 将每个 batch 的 2D 输出「拼回」3D 体数据
    5. 按视角权重累加到 prediction_probability

    视角权重：
    - Axial:    0.4（最重要的视角）
    - Coronal:  0.4（和轴向同等重要）
    - Sagittal: 0.2（由于类别数较少，权重减半）
    """
    # 构建 DataLoader：每个样本是一个 2D 切片，
    # 但通道是「多模态 × 厚切片(7)」拼接结果。
    test_dataset = OrigDataThickSlices_Fused_Input(img_filename, orig_data, plane=plane,
                                                   transforms=transforms.Compose(ToTensorTest()))
    # shuffle=False：推理时切片顺序必须保持不变，否则无法拼回 3D
    test_data_loader = DataLoader(dataset=test_dataset, shuffle=False, batch_size=params_model["batch_size"])
    total_batches = len(test_data_loader)

    logger.info("  -Loading {} Net from {}".format(plane, ckpts))

    # 保留已加载的模态 backbone，只刷新当前视角对应的融合头权重。
    # 这样能减少重复加载开销，同时保持每个视角主头参数正确。
    backbones = copy.deepcopy(model.FastSurferCNNs)

    # 加载主网络权重
    model_state = torch.load(ckpts, map_location=torch.device('cpu'))

    # 处理 state_dict 中可能存在的 "module." 前缀
    # 如果训练时用了 DataParallel，key 会包含 "module." 前缀
    # 推理时可能不用 DataParallel，需要去掉这个前缀
    new_state_dict = OrderedDict()
    for k, v in model_state["model_state_dict"].items():
        if k[:7] == "module." and not params_model["model_parallel"]:
            new_state_dict[k[7:]] = v
        elif k[:7] != "module." and params_model["model_parallel"]:
            new_state_dict["module." + k] = v
        else:
            new_state_dict[k] = v
    model.load_state_dict(new_state_dict)

    print('Load backbones!')
    model.FastSurferCNNs = backbones
    model.eval()

    logger.info("  -{} model loaded.".format(plane))
    with torch.no_grad():

        # start_index 记录当前写入 3D 体素网格中的切片位置。
        # 因为网络逐批处理 2D 切片，需要把每批结果「拼回」3D。
        start_index = 0
        for batch_idx, sample_batch in enumerate(test_data_loader):
            if batch_idx == 0 or (batch_idx + 1) == total_batches or (batch_idx + 1) % 10 == 0:
                logger.info(
                    "  -{} progress: batch {}/{} ({:.1f}%)".format(
                        plane, batch_idx + 1, total_batches, 100.0 * (batch_idx + 1) / total_batches
                    )
                )

            images_batch = Variable(sample_batch["image"])
            images_batch = images_batch.to(params_model["device"])

            # 模型返回：主 logits + 各分支 logits 的列表
            temp, temp_list = model(images_batch)

            # ★ 对每个分支的输出分别累加到 pred_prob 的对应位置
            for t_idx, temp in enumerate(temp_list):
                start_index_tmp = start_index
                if plane == "Axial":
                    # 轴向：切片沿 z 方向堆叠。
                    # 网络输出 [B, C, H, W]，需要转回 3D 体素网格
                    # permute 将维度从 (B, C, H, W) 变为 (C, B, H, W)
                    # 其中 B 对应 3D 中 z 方向的一段切片
                    temp = temp.permute(3, 0, 2, 1)
                    prediction_probability[t_idx, :, start_index_tmp:start_index_tmp + temp.shape[1], :, :] += torch.mul(temp.cpu(), 0.4)
                    start_index_tmp += temp.shape[1]

                elif plane == "Coronal":
                    # 冠状：切片沿 y 方向堆叠
                    temp = temp.permute(2, 3, 0, 1)
                    prediction_probability[t_idx, :, :, start_index_tmp:start_index_tmp + temp.shape[2], :] += torch.mul(temp.cpu(), 0.4)
                    start_index_tmp += temp.shape[2]

                else:
                    # 矢状：切片沿 x 方向堆叠。
                    # 注意矢状网络输出的是缩减类别空间，
                    # 需要用 map_prediction_sagittal2full 映射回完整类别空间。
                    temp = map_prediction_sagittal2full(temp).permute(0, 3, 2, 1)
                    prediction_probability[t_idx, start_index_tmp:start_index_tmp + temp.shape[0], :, :, :] += torch.mul(temp.cpu(), 0.2)
                    start_index_tmp += temp.shape[0]

            start_index = start_index_tmp

        logger.info("  -{} inference done.".format(plane))

    return prediction_probability


# =========================================================================
# fastsurfercnn — 主推理函数 ★ 入口
# =========================================================================
def fastsurfercnn(img_filename, save_as, logger, args):
    """
    DDParcel 的主推理函数，包含完整的推理流程。

    步骤概览：
    1. 选择设备（cuda/mps/cpu）
    2. 读取并 conform 所有输入体数据
    3. 依次运行 Axial/Coronal/Sagittal 三个模型并加权融合
    4. 做标签空间映射与后处理
    5. 保存最终 mgz 分割结果

    :param img_filename: 输入文件路径列表
    :param save_as: 输出 mgz 文件路径
    :param logger: 日志记录器
    :param args: 命令行参数
    """
    start_total = time.time()

    # 公开 DDSurfer 权重对应的共享网络参数。
    params_network = {'num_channels': args.num_channels, 'num_filters': args.num_filters, "num_modality": args.num_modality, "backbone_model": args.backbone_axial_path,
                      'kernel_h': args.kernel_height, 'kernel_w': args.kernel_width,
                      'stride_conv': args.stride, 'pool': args.pool,
                      'stride_pool': args.stride_pool, 'num_classes': args.num_classes_ax_cor,
                      'kernel_c': 1, 'kernel_d': 1}

    # ──────────── 设备选择 ────────────
    # auto 模式按优先级：CUDA → MPS(Apple Silicon) → CPU
    if args.device == 'auto':
        if (not args.no_cuda) and torch.cuda.is_available():
            device = torch.device("cuda")
        elif torch.backends.mps.is_available():
            device = torch.device("mps")
        else:
            device = torch.device("cpu")
    elif args.device == 'cuda':
        if args.no_cuda or (not torch.cuda.is_available()):
            raise RuntimeError("CUDA requested but not available (or disabled by --no_cuda).")
        device = torch.device("cuda")
    elif args.device == 'mps':
        if not torch.backends.mps.is_available():
            raise RuntimeError("MPS requested but not available on this machine/PyTorch build.")
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    if device.type == "cuda" and args.gpu != '-1':
        os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu

    print("On GPU ({})!".format(device.type.upper())) if device.type in ("cuda", "mps") else print("On CPU ...")

    if device.type == "cuda" and torch.cuda.device_count() > 1:
        model_parallel = False
    else:
        model_parallel = False

    params_model = {'device': device, "use_cuda": device.type == "cuda", "batch_size": args.batch_size, "model_parallel": model_parallel}
    logger.info("Cuda available: {}, # Available GPUS: {}, MPS available: {}, Cuda user disabled (--no_cuda flag): {}, --> Using device: {}".format(
        torch.cuda.is_available(), torch.cuda.device_count(), torch.backends.mps.is_available(), args.no_cuda, device))

    # ──────────── 概率累加张量 ────────────
    # pred_prob 的形状：(num_modality+2, 256, 256, 256, num_classes)
    #
    # dim0 (分支维) 包含：
    # - [0]: 主融合网络的输出（加权后的）
    # - [1..num_modality]: 各 backbone 的独立输出
    # - [-1]: 一个额外的累加槽位
    #
    # 待融合后的三个视角结果，在 dim0=0 上对三视角做 argmax。
    # 可以把它理解成「多路投票箱」。
    pred_prob = torch.zeros((args.num_modality+2, 256, 256, 256, args.num_classes_ax_cor), dtype=torch.float)

    # ──────────── 读取并 conform 所有输入 ────────────
    # 注意 orig_data 以列表形式保存所有模态的 3D numpy 数组
    orig_data = []
    for idx in range(len(img_filename)):
        header_info, affine_info, orig_data_ = load_and_conform_image(img_filename[idx], interpol=1, logger=logger)
        orig_data.append(orig_data_)
        logger.info("Reading volume {}".format(img_filename[idx]))
        del orig_data_

    # ═══════════════════════════════════════════════════════════════
    # 视角 1：轴状面（Axial）
    # ═══════════════════════════════════════════════════════════════
    # 权重 0.4 — 三个视角中最重要的视角之一
    params_network["num_classes"] = args.num_classes_ax_cor
    params_network["num_channels"] = args.num_channels
    params_network["backbone_model"] = args.backbone_axial_path
    params_network["use_cuda"] = device.type == "cuda"
    model = FastSurferCNN_Fuse_Unet_v3_extended(params_network)
    if model_parallel:
        model = nn.DataParallel(model)
    model.to(device)
    start = time.time()
    pred_prob = run_network(img_filename, orig_data, pred_prob, "Axial", args.network_axial_path, params_model, model, logger)
    logger.info("Axial View Tested in {:0.4f} seconds".format(time.time() - start))

    # ═══════════════════════════════════════════════════════════════
    # 视角 2：冠状面（Coronal）
    # ═══════════════════════════════════════════════════════════════
    # 权重 0.4 — 和轴向同等重要
    params_network["num_classes"] = args.num_classes_ax_cor
    params_network["num_channels"] = args.num_channels
    params_network["backbone_model"] = args.backbone_coronal_path
    model = FastSurferCNN_Fuse_Unet_v3_extended(params_network)
    if model_parallel:
        model = nn.DataParallel(model)
    model.to(device)
    start = time.time()
    pred_prob = run_network(img_filename, orig_data, pred_prob, "Coronal", args.network_coronal_path, params_model, model, logger)
    logger.info("Coronal View Tested in {:0.4f} seconds".format(time.time() - start))

    # ═══════════════════════════════════════════════════════════════
    # 视角 3：矢状面（Sagittal）
    # ═══════════════════════════════════════════════════════════════
    # 权重 0.2 — 因为矢状面网络使用更少的类别（54 vs 82），
    # 在左右标签的分辨能力上弱一些，所以权重减半
    params_network["num_classes"] = args.num_classes_sag
    params_network["num_channels"] = args.num_channels
    params_network["backbone_model"] = args.backbone_sagittal_path
    model = FastSurferCNN_Fuse_Unet_v3_extended(params_network)
    if model_parallel:
        model = nn.DataParallel(model)
    model.to(device)
    start = time.time()
    pred_prob = run_network(img_filename, orig_data, pred_prob, "Sagittal", args.network_sagittal_path, params_model, model, logger)
    logger.info("Sagittal View Tested in {:0.4f} seconds".format(time.time() - start))

    # ═══════════════════════════════════════════════════════════════
    # 后处理 1：取 argmax → 标签映射
    # ═══════════════════════════════════════════════════════════════
    # 取第 0 个分支（主融合结果）
    # 在最后维度（类别维）取 argmax，得到每个体素的类别索引
    pred_prob = pred_prob[0]
    _, pred_prob = torch.max(pred_prob, 3)
    pred_prob = pred_prob.numpy()
    # 将内部类别索引（0~81）映射到 FreeSurfer 标签（2, 41, 1001...）
    pred_prob = map_label2aparc_aseg(pred_prob)

    # ═══════════════════════════════════════════════════════════════
    # 后处理 2：半球判定纠错
    # ═══════════════════════════════════════════════════════════════
    # 某些皮层标签的左右半球可能有混淆（如左脑标签出现在右脑位置）。
    # 下面是基于「白质质心」的纠错策略：
    #
    # 1. 找到左脑白质（标签 2）和右脑白质（标签 41）的最大连通域
    # 2. 计算两个白质区域的质心
    # 3. 对皮层标签列表中的每个标签，计算其每个连通域的质心
    # 4. 该连通域离哪个白质质心近，就分配对应半球的标签
    #
    # 比如：某个 1001（左上颞）的连通域，如果质心靠近右白质中心，
    # 就将其改为 2001（右上颞）。
    rh_wm = get_largest_cc(pred_prob == 41)   # 右脑白质
    lh_wm = get_largest_cc(pred_prob == 2)    # 左脑白质
    rh_wm = regionprops(label(rh_wm, background=0))
    lh_wm = regionprops(label(lh_wm, background=0))
    centroid_rh = np.asarray(rh_wm[0].centroid)
    centroid_lh = np.asarray(lh_wm[0].centroid)

    # 需要按半球质心距离拆分的皮层候选标签列表（只包含左脑标签）
    # 这些标签在矢状面附近可能被错误分配到对侧半球
    labels_list = np.array([1001, 1003, 1006, 1007, 1008, 1009, 1011,
                            1015, 1018, 1019, 1020, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035])

    for label_current in labels_list:
        label_img = label(pred_prob == label_current, connectivity=3, background=0)
        for region in regionprops(label_img):
             if region.label != 0:
                # 计算该连通域到左右白质质心的距离
                # 离哪个较近就分配到哪个半球
                if np.linalg.norm(np.asarray(region.centroid) - centroid_rh) < np.linalg.norm(np.asarray(region.centroid) - centroid_lh):
                    mask = label_img == region.label
                    # 右脑标签 = 左脑标签 + 1000
                    pred_prob[mask] = label_current + 1000

    # ═══════════════════════════════════════════════════════════════
    # 后处理 3：高斯平滑纠错（针对易混淆类别）
    # ═══════════════════════════════════════════════════════════════
    # 用平滑后的左右白质先验（Gaussian blur）来修复易重叠类别。
    #
    # 思路：对一个体素，看它更靠近左脑白质中心还是右脑白质中心，
    # 以此来决定该位置的皮层标签应该是左还是右。
    # 高斯模糊使这个决策边界更平滑，避免硬边界。
    #
    # 这相当于在左右边界附近做一次「软约束」纠错。
    aseg_lh = gaussian_filter(1000 * np.asarray(pred_prob == 2, dtype=np.float32), sigma=3)
    aseg_rh = gaussian_filter(1000 * np.asarray(pred_prob == 41, dtype=np.float32), sigma=3)
    # lh_rh_split: 0=更靠左白质, 1=更靠右白质
    lh_rh_split = np.argmax(np.concatenate((np.expand_dims(aseg_lh, axis=3), np.expand_dims(aseg_rh, axis=3)), axis=3), axis=3)

    # 以下类别在左右半球最容易混淆，需要特别处理
    for prob_class_lh in [1011, 1019, 1026, 1029, 1032]:
        prob_class_rh = prob_class_lh + 1000

        mask_lh = ((pred_prob == prob_class_lh) | (pred_prob == prob_class_rh)) & (lh_rh_split == 0)
        mask_rh = ((pred_prob == prob_class_lh) | (pred_prob == prob_class_rh)) & (lh_rh_split == 1)

        pred_prob[mask_lh] = prob_class_lh
        pred_prob[mask_rh] = prob_class_rh

    # ═══════════════════════════════════════════════════════════════
    # 后处理 4：可选清理（小连通域替换为中值滤波）
    # ═══════════════════════════════════════════════════════════════
    # 目的：去掉零散噪声小块，得到更连续的解剖结构。
    # 对每个标签的连通域，如果面积 ≤ tolerance，用 3×3×3 中值滤波值替换。
    if args.cleanup is True:

        labels = [2, 4, 5, 7, 8, 10, 11, 12, 13, 14,
                  15, 16, 17, 18, 24, 26, 28, 31, 41, 43, 44,
                  46, 47, 49, 50, 51, 52, 53, 54, 58, 60, 63,
                  77, 1026, 2026]

        start = time.time()
        pred_prob_medfilt = median_filter(pred_prob, size=(3, 3, 3))
        mask = np.zeros_like(pred_prob)
        tolerance = 25

        for current_label in labels:
            current_class = (pred_prob == current_label)
            label_image = label(current_class, connectivity=3)

            for region in regionprops(label_image):
                if region.area <= tolerance:
                    mask_label = (label_image == region.label)
                    mask[mask_label] = 1

        pred_prob[mask == 1] = pred_prob_medfilt[mask == 1]
        logger.info("Segmentation Cleaned up in {:0.4f} seconds.".format(time.time() - start))

    # 将背景体素（normalize.py 中设为 -4）重新置 0
    pred_prob[orig_data[0] == -4] = 0

    # ──────────── 保存结果 ────────────
    # 输出 mgz 格式，使用整型（int16）存储标签
    header_info.set_data_dtype(np.int16)
    mapped_aseg_img = nib.MGHImage(pred_prob, affine_info, header_info)
    mapped_aseg_img.to_filename(save_as)

    logger.info("Saving Segmentation to {}".format(save_as))
    logger.info("Total processing time: {:0.4f} seconds.".format(time.time() - start_total))


# =========================================================================
# 主程序入口
# =========================================================================
if __name__ == "__main__":

    # 解析命令行参数
    options = options_parse()

    # 设置日志记录器
    logger = logging.getLogger("eval")
    logger.setLevel(logging.DEBUG)
    logger.addHandler(logging.StreamHandler(stream=sys.stdout))

    # 启动推理
    fastsurfercnn(options.iname, options.oname, logger, options)
